00_LoginPage/Models/Product.cs
using System.ComponentModel.DataAnnotations.Schema;

namespace _00_LoginPage.Models;

public class Product : BaseEntity
{
    public string Name { get; set; } = null!;
    public string Description { get; set; }
    public string Color { get; set; }
    public decimal Price { get; set; }
    public string ImageUrl { get; set; }
    public int CategoryId { get; set; }
    private Product()
    {
        
    }

    public Product(string name, string description,string color,decimal price,string url, int categoryId)
    {
        this.Name = name;
        this.Description = description;
        this.Color = color;
        this.Price = price;
        this.ImageUrl = url;
        this.CategoryId = categoryId;
    }
    public virtual Category Category { get; set; } = null!;
}

00_LoginPage/Controllers/CategoryController.cs
using _00_LoginPage.Context;
using _00_LoginPage.Models;
using _00_LoginPage.Models.InsertModel.Models;
using _00_LoginPage.Models.UpdateModel.Models;
using _00_LoginPage.ViewModeels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Security.Claims;

namespace _00_LoginPage.Controllers
{
    public class CategoryController : Controller
    {
        private readonly ShoppingDbContext _userDbContext;
        public CategoryController(ShoppingDbContext dbContext)
        {
            _userDbContext = dbContext;
        }
        public IActionResult Index()
        {
            IReadOnlyList<CategoryViewModel> CategoryView = (from category in _userDbContext.Categories
                                                             join product in _userDbContext.Products
                                                                 on category.Id equals product.Id
                                                             into prd from product in prd.DefaultIfEmpty()
                                                             select new CategoryViewModel()
                                                             {
                                                                 Id = category.Id,
                                                                 Name = category.Name,
                                                                 ImageUrl = category.ImageUrl,
                                                             }).ToList();
                                                            
                                                            

            return View(CategoryView);
        }
        //Admin Controller
        [HttpGet]
        public IActionResult Create()
        {
            CategoryInsertModel category = new CategoryInsertModel();
            return View(category);
        }

        [HttpPost]
        public IActionResult Create(CategoryInsertModel input)
        {
            var newCategory = new Category(input.Name, input.ImageUrl);

            _userDbContext.Categories.Add(newCategory);
            _userDbContext.SaveChanges();

            return RedirectToAction("Index");
        }


        public IActionResult Update(int id)
        {
            var category = _userDbContext.Categories.SingleOrDefault(x => x.Id == id);

            // Null Check
            if (category == null)
            {
                throw new NullReferenceException();
            }

            CategoryUpdateModel categoryUpdate = new CategoryUpdateModel();
            categoryUpdate.Name = category.Name;
            categoryUpdate.ImageUrl = category.ImageUrl;
            return View(categoryUpdate);
        }

        [HttpPost]
        //[Route("/category/update/{id}")]
        public IActionResult Update(CategoryUpdateModel input, int id)
        {
            // Get Category
            var category = _userDbContext.Categories.SingleOrDefault(x => x.Id == id);

            // Null Check
            if(category == null)
            {
                throw new NullReferenceException();
            }

            // Update Category
            category.Name = input.Name;
            category.ImageUrl = input.ImageUrl;

            _userDbContext.Update(category);
            _userDbContext.SaveChanges();

            return RedirectToAction("Index");
        }

        public IActionResult Delete(int id)
        {
            var categoryCheck = _userDbContext.Categories.FirstOrDefault(x => x.Id == id);
            if(categoryCheck != null)
            {
                _userDbContext.Categories.Remove(categoryCheck);
                _userDbContext.SaveChanges();
            }
            return RedirectToAction("Index");
        }
    }
}

00_LoginPage/Controllers/ShoppingListController.cs
using _00_LoginPage.Context;
using _00_LoginPage.Models;
using _00_LoginPage.Models.InsertModel.Models;
using _00_LoginPage.Models.UpdateModel.Models;
using _00_LoginPage.ViewModeels;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace _00_LoginPage.Controllers
{
    public class ShoppingListController : Controller
    {
        private readonly ILogger<ShoppingListController> _logger;
        private readonly ShoppingDbContext _userDbContext;
        private readonly string _cookieName;
        public ShoppingListController(ILogger<ShoppingListController> logger, ShoppingDbContext userDbContext)
        {
            _logger = logger;
            _userDbContext = userDbContext;
            _cookieName = ".AspNetCore." + CookieAuthenticationDefaults.AuthenticationScheme;
        }

        public IActionResult Index([FromQuery(Name = "shoppinglistid")] int shoppingListId)
        {
            var userId = User.Claims.First(c => c.Type == ClaimTypes.NameIdentifier);

            if (userId == null)
            {
                throw new ArgumentException();
            }

            IEnumerable<ShoppingListViewModel> ShoppingList = (from shoppingList in _userDbContext.ShoppingLists
                                                               join shoppingListProduct in _userDbContext.ShoppingListProducts
                                                                   on shoppingList.Id equals shoppingListProduct.ShoppingListId
                                                               into slp from shoppingListProduct in slp.DefaultIfEmpty()
                                                               where shoppingList.UserId == int.Parse(userId.Value)
                                                               select new ShoppingListViewModel()
                                                               {
                                                                   Id = shoppingList.Id,
                                                                   Name = shoppingList.Name,
                                                                   IsEditable = shoppingList.IsEditable,
                                                                   Products = shoppingList.ShoppingListProducts.Select(x => new ShoppingListProductViewModel()
                                                                   {
                                                                       Id = x.Id,
                                                                       Amount = x.Amount,
                                                                       IsAddedToCart = x.IsAddedToCart,
                                                                       ShoppingListId = x.ShoppingListId,
                                                                       Product = new ProductViewModel()
                                                                       {
                                                                           Id = x.ProductId,
                                                                           Name = x.Product.Name,
                                                                           Color = x.Product.Color,
                                                                           Description = x.Product.Description,
                                                                           ImageUrl = x.Product.ImageUrl,
                                                                           Price = x.Product.Price,
                                                                           Category = new CategoryViewModel()
                                                                           {
                                                                               Id = x.Product.Category.Id,
                                                                               Name = x.Product.Category.Name,
                                                                           }

                                                                       }
                                                                   }).ToList(),
                                                               }).ToList();

            var list = ShoppingList.DistinctBy(x => x.Id).ToList();

            return View(list);
        }

        [HttpPost]
        public IActionResult Index(ShoppingListViewModel shoppingListViewModel)
        {
            var isEditable = shoppingListViewModel.IsEditable;
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult IsEditableToFalse(int id)
        {
            var appt = _userDbContext.ShoppingLists.Single(x => x.Id == id);
            appt.IsEditable = false;
            _userDbContext.ShoppingLists.Update(appt);
            _userDbContext.SaveChanges();
            return RedirectToAction("Index");   
        }

        [HttpPost]
        public ActionResult IsEditableToTrue(int id)
        {
            var appt = _userDbContext.ShoppingLists.Single(x => x.Id == id);
            appt.IsEditable = true;
            _userDbContext.ShoppingLists.Update(appt);
            _userDbContext.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Create()
        {
            ShoppingListInsertModel shoppingList = new ShoppingListInsertModel();
            return View(shoppingList);
        }

        [HttpPost]
        public ActionResult Create(ShoppingListInsertModel input)
        {
            var userId = User.Claims.First(c => c.Type == ClaimTypes.NameIdentifier);
            
            if ( userId == null )
            {
                throw new ArgumentException();
            }

            var shoppingList = new ShoppingList(input.Name,int.Parse(userId.Value));

            // 2. Save this shopping list to the database
            _userDbContext.ShoppingLists.Add(shoppingList);
            _userDbContext.SaveChanges();

            //Request.Cookies[_cookieName].

            //if (HttpContext.Request.Cookies.TryGetValue(".AspNetCore." + CookieAuthenticationDefaults.AuthenticationScheme, out string? value))
            //{
            //    return View();
            //}


            // 4. Redirect user to the "user/index" page in order to list shooping lists
            return RedirectToAction("Index");
        }


        public IActionResult Delete(int id)
        {
            var shoppingListCheck = _userDbContext.ShoppingLists.SingleOrDefault(x => x.Id == id);
            if(shoppingListCheck != null)
            {
                _userDbContext.ShoppingLists.Remove(shoppingListCheck); 
                _userDbContext.SaveChanges();
            }

            return RedirectToAction("Index");
        }

    }
}

00_LoginPage/Controllers/ShoppingListProductController.cs
using _00_LoginPage.Context;
using _00_LoginPage.Models;
using _00_LoginPage.Models.InsertModel.Models;
using _00_LoginPage.Models.UpdateModel.Models;
using _00_LoginPage.ViewModeels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;

namespace _00_LoginPage.Controllers
{
    public class ShoppingListProductController : Controller
    {
        private readonly ShoppingDbContext _userDbContext;

        public ShoppingListProductController(ShoppingDbContext context)
        {
            _userDbContext = context;
        }

        public IActionResult Index([FromQuery(Name = "shoppinglistid")] int shoppingListId, [FromQuery(Name ="searching")] string searching, [FromQuery(Name ="category")] string category)
        {
            IReadOnlyList<ShoppingListProductViewModel> shoppingListProducts = _userDbContext.ShoppingListProducts.Where(x => x.ShoppingListId == shoppingListId)
                .Select(x => new ShoppingListProductViewModel()
            {
                Id = x.Id,
                Amount = x.Amount,
                Name = x.Product.Name,
                ImageUrl = x.Product.ImageUrl,
                IsAddedToCart = x.IsAddedToCart,
                ShoppingListId = x.ShoppingListId,
                Product = new ProductViewModel()
                {
                    Id = x.Id,
                    ImageUrl = x.Product.ImageUrl,
                    Color = x.Product.Color,
                    Description = x.Description,
                    Price = x.Product.Price,
                    Category = new CategoryViewModel()
                    {
                        Name = x.Product.Category.Name,
                        Id = x.Id,
                    }
                }

            }).ToList();


            if (!String.IsNullOrEmpty(searching))
            {
                shoppingListProducts = shoppingListProducts.Where(x => x.Name.ToLower().Contains(searching.ToLower())).ToList();
            }

            if(!String.IsNullOrEmpty(category))
            {
                shoppingListProducts = shoppingListProducts.Where(x => x.Product.Category.Name.ToLower().Contains(category.ToLower())).ToList();
            }

            return View(shoppingListProducts);

        }

        [HttpPost]
        public ActionResult IsAddedToTrue(int id)
        {
            var isAddedTocart = _userDbContext.ShoppingListProducts.SingleOrDefault(x => x.Id == id);
            isAddedTocart.IsAddedToCart = true;
            _userDbContext.ShoppingListProducts.Update(isAddedTocart);
            _userDbContext.SaveChanges();
            return RedirectToAction(nameof(Index),new {shoppinglistid = isAddedTocart.ShoppingListId});
        }

        [HttpGet]
        public IActionResult Create([FromQuery(Name ="productid")] int productId, [FromQuery(Name ="shoppinglistid")] int shoppingListId)
        {
            var model = new ShoppingListProductInsertModel() { ProductId = productId, ShoppingListId = shoppingListId};


            if (model == null)
            {
                throw new NullReferenceException();
            }

            return View(model);
        }


        [HttpPost]
        public IActionResult Create(ShoppingListProductInsertModel input, int id)
        {
            var newShoppingListProducts = new ShoppingListProduct();
            var isEditableCheck = _userDbContext.ShoppingLists.SingleOrDefault(x => x.Id == input.ShoppingListId);

            if (newShoppingListProducts == null)
            {
                throw new NullReferenceException();
            }

            if(isEditableCheck.IsEditable == true)
            {
                newShoppingListProducts.ShoppingListId = input.ShoppingListId;
                newShoppingListProducts.Amount = input.Amount;
                newShoppingListProducts.ProductId = input.ProductId;
                newShoppingListProducts.Description = input.Description;

                _userDbContext.ShoppingListProducts.Add(newShoppingListProducts);
                _userDbContext.SaveChanges();

                return this.RedirectToAction("Index", new { shoppinglistid = input.ShoppingListId });
            }
            else
            {
                throw new Exception("İsteğiniz Reddedildi");
            }

        }





        [HttpGet]
        public IActionResult Update(int id)
        {
            var shoppingListProducts = _userDbContext.ShoppingListProducts.SingleOrDefault(x => x.Id == id);  

           if(shoppingListProducts == null)
            {
                throw new NullReferenceException();
            }

            ShoppingListProductUpdateModel updateShoppingListProducts = new ShoppingListProductUpdateModel();

            shoppingListProducts.Amount = updateShoppingListProducts.Amount;
            return View(shoppingListProducts);
        }

        [HttpPost]
        public IActionResult Update(ShoppingListProductUpdateModel input, int id)
        {
            var shoppingListProducts = _userDbContext.ShoppingListProducts.SingleOrDefault(x => x.Id == id);    

            shoppingListProducts.Amount = input.Amount;
            shoppingListProducts.Description = input.Description;

            _userDbContext.Update(shoppingListProducts);
            _userDbContext.SaveChanges();
            return RedirectToAction("Index");
        }

        public IActionResult Delete(int id)
        {
            var shoppingListProductsCheck = _userDbContext.ShoppingListProducts.SingleOrDefault(x => x.Id == id);

            if(shoppingListProductsCheck != null)
            {
                _userDbContext.Remove(shoppingListProductsCheck);
                _userDbContext.SaveChanges();
            }

            return RedirectToAction("Index", new {shoppinglistid = shoppingListProductsCheck.ShoppingListId});
        }
    }
}

00_LoginPage/Views/Product/AdminProducts.cshtml
@model ICollection<_00_LoginPage.ViewModeels.ProductViewModel>
@{
    ViewBag.Title = "Ürünler";
}

<div class="conatiner">
    <div class="wrap">
        @foreach (var item in Model)
        {
            <div class="box one m-4">
                <h2 class="mt-2">@item.Name</h2>
                <img class="card-img-top mt-1" src="@Url.Content(item.ImageUrl)">
                <div class="container-login100-form-btn m-3">
                    <div class="wrap-login100-form-btn">
                        <div class="login100-form-bgbtn"></div>
                        <button type="submit" asp-action="Update" asp-controller="Product" class="login100-form-btn">
                            <a asp-controller="Product" class="login100-form-btn" asp-action="Update" asp-route-id="@item.Id">
                                Değiştir
                            </a>
                        </button>
                    </div>
                </div>
                <div class="container-login100-form-btn m-4">
                    <div class="wrap-login100-form-btn">
                        <div class="login100-form-bgbtn"></div>
                        @using (Html.BeginForm("Delete", "Product", new { id = item.Id }, FormMethod.Post))
                        {
                            <button type="submit" class="login100-form-btn">
                                Sil
                            </button>
                        }
                    </div>
                </div>
            </div>
        }
    </div>
</div>

00_LoginPage/Views/Product/Create.cshtml
@model _00_LoginPage.ViewModel.ProductInsertViewModel
@{
    ViewBag.Title = "Yeni Ürün Oluştur";
}

<!DOCTYPE html>
<html lang="tr">
<head>

</head>
<body>
    <div class="limiter">
        <div class="container-login100">
            <div class="wrap-login100 p-l-55 p-r-55 p-t-65 p-b-54">
                @using (Html.BeginForm("Create", "Product", FormMethod.Post))
                {
                    <form class="login100-form validate-form">
                        <span class="login100-form-title p-b-49">
                            Ürün Oluştur
                        </span>
                        <div class="wrap-input100 validate-input m-b-23" data-validate="Username is reauired">
                            <span class="label-input100">Ad</span>
                            <input class="input100" type="text" asp-for="Name" placeholder="Ürün Adı" required>
                            <span class="focus-input100" data-symbol="&#xf1db;"></span>
                        </div>
                        <div class="wrap-input100 validate-input m-b-23" data-validate="Username is reauired">
                            <span class="label-input100">Açıklama</span>
                            <input class="input100" type="text" asp-for="Description" placeholder="Ürün Açıklaması" required>
                            <span class="focus-input100" data-symbol="&#xf1db;"></span>
                        </div>
                        <div class="wrap-input100 validate-input m-b-23" data-validate="Username is reauired">
                            <span class="label-input100">Renk</span>
                            <input class="input100" type="text" asp-for="Color" placeholder="Ürün Rengi" required>
                            <span class="focus-input100" data-symbol="&#xf1db;"></span>
                        </div>
                        <div class="wrap-input100 validate-input m-b-23" data-validate="Username is reauired">
                            <span class="label-input100">Fiyat</span>
                            <input class="input100" type="number" asp-for="Price" placeholder="Ürün Fiyatı" required>
                            <span class="focus-input100" data-symbol="&#xf1db;"></span>
                        </div>
                        <div class="wrap-input100 validate-input m-b-23" data-validate="Username is reauired">
                            <span class="label-input100">Kategori</span>
                            <select class="input100" asp-for="CategoryId">
                                @foreach (var category in Model.Categories)
                                {
                                    <option value="@category.Id">@category.Name</option>
                                }
                            </select>
                            <span class="focus-input100" data-symbol="&#xf1db;"></span>
                        </div>
                        <div class="wrap-input100 validate-input m-b-23" data-validate="Username is reauired">
                            <span class="label-input100">Resim URL</span>
                            <input class="input100" type="url" asp-for="ImageUrl" placeholder="Resim URL" required>
                            <span class="focus-input100" data-symbol="&#xf22c;"></span>
                        </div>
                        <div class="container-login100-form-btn">
                            <div class="wrap-login100-form-btn">
                                <div class="login100-form-bgbtn"></div>
                                <button type="submit" asp-action="Create" asp-controller="Product" class="login100-form-btn">
                                    Oluştur
                                </button>
                            </div>
                            @if (!ViewData.ModelState.IsValid)
                            {
                                <span class="text-center text-danger">
                                    @foreach (var modelState in ViewData.ModelState.Values)
                                    {
                                        foreach (var error in modelState.Errors)
                                        {
                                            <li>@error.ErrorMessage</li>
                                        }
                                    }
                                </span>
                            }
                        </div>
                        <div class="flex-col-c p-t-155">
                            <span class="txt1 p-b-17">
                                Kategori Listesine Geri Dönmek İster Misiniz?
                            </span>
                            <a asp-action="Index" asp-controller="Category" class="txt2">
                                Kategoriler
                            </a>
                        </div>
                    </form>
                }
            </div>
        </div>
    </div>
    <div id="dropDownSelect1"></div>
</body>
</html>

00_LoginPage/Views/Product/Update.cshtml
@model _00_LoginPage.Models.UpdateModel.Models.ProductUpdateModel
@{
    ViewBag.Title = "Ürünü Düzenle";
}

<!DOCTYPE html>
<html lang="tr">
<head>

</head>
<body>
    <div class="limiter">
        <div class="container-login100">
            <div class="wrap-login100 p-l-55 p-r-55 p-t-65 p-b-54">
                @using (Html.BeginForm("Update", "Product", FormMethod.Post))
                {
                    <form class="login100-form validate-form">
                        <span class="login100-form-title p-b-49">
                            Ürün Oluştur
                        </span>
                        <div class="wrap-input100 validate-input m-b-23" data-validate="Username is reauired">
                            <span class="label-input100">Ad</span>
                            <input class="input100" type="text" asp-for="Name" placeholder="Ürün Adı" required>
                            <span class="focus-input100" data-symbol="&#xf1db;"></span>
                        </div>
                        <div class="wrap-input100 validate-input m-b-23" data-validate="Username is reauired">
                            <span class="label-input100">Açıklama</span>
                            <input class="input100" type="text" asp-for="Description" placeholder="Ürün Açıklaması" required>
                            <span class="focus-input100" data-symbol="&#xf1db;"></span>
                        </div>
                        <div class="wrap-input100 validate-input m-b-23" data-validate="Username is reauired">
                            <span class="label-input100">Renk</span>
                            <input class="input100" type="text" asp-for="Color" placeholder="Ürün Rengi" required>
                            <span class="focus-input100" data-symbol="&#xf1db;"></span>
                        </div>
                        <div class="wrap-input100 validate-input m-b-23" data-validate="Username is reauired">
                            <span class="label-input100">Fiyat</span>
                            <input class="input100" type="number" asp-for="Price" placeholder="Ürün Fiyatı" required>
                            <span class="focus-input100" data-symbol="&#xf1db;"></span>
                        </div>
                        <div class="wrap-input100 validate-input m-b-23" data-validate="Username is reauired">
                            <span class="label-input100">Resim URL</span>
                            <input class="input100" type="url" asp-for="ImageUrl" placeholder="Resim URL" required>
                            <span class="focus-input100" data-symbol="&#xf22c;"></span>
                        </div>
                        <div class="container-login100-form-btn">
                            <div class="wrap-login100-form-btn">
                                <div class="login100-form-bgbtn"></div>
                                <button type="submit" asp-action="Update" asp-controller="Product" class="login100-form-btn">
                                    Oluştur
                                </button>
                            </div>
                            @if (!ViewData.ModelState.IsValid)
                            {
                                <span class="text-center text-danger">
                                    @foreach (var modelState in ViewData.ModelState.Values)
                                    {
                                        foreach (var error in modelState.Errors)
                                        {
                                            <li>@error.ErrorMessage</li>
                                        }
                                    }
                                </span>
                            }
                        </div>
                        <div class="flex-col-c p-t-155">
                            <span class="txt1 p-b-17">
                                Ürünlere Geri Dönmek İster Misiniz?
                            </span>
                            <a asp-action="Index" asp-controller="Product" class="txt2">
                                Ürünler
                            </a>
                        </div>
                    </form>
                }
            </div>
        </div>
    </div>
    <div id="dropDownSelect1"></div>
</body>
</html>

00_LoginPage/Views/Product/UserProducts.cshtml
@model ICollection<_00_LoginPage.ViewModeels.ProductViewModel>

@{
    ViewBag.Title = "Ürünler";
}

<div class="conatiner">
    <div class="back-to-shop"><a asp-action="Index" asp-controller="ShoppingList">&leftarrow;</a><span class="text-bold"><b>Sipariş Listelerime Geri Dön</b></span></div>
    <div class="wrap">
            @foreach (var item in Model)
            {

                @using (Html.BeginForm("Create", "ShoppingListProduct", FormMethod.Post))
                    {
                    <div class="box one m-4">
                        <h2 class="mt-4 pt-4">@item.Name</h2>
                        <img class="card-img-top mt-3" src="@Url.Content(item.ImageUrl)">
                        <div class="container-login100-form-btn m-3">
                            <div class="wrap-login100-form-btn">
                                <div class="login100-form-bgbtn"></div>
                                <button type="submit" asp-action="Create" asp-controller="ShoppingListProduct" class="login100-form-btn">
                                    <a asp-controller="ShoppingListProduct" class="login100-form-btn" asp-action="Create" asp-route-shoppinglistid="@item.ShoppingListId" asp-route-productid="@item.ProductId">
                                            Ekle
                                    </a>
                                </button>
@*                                <div class="form-group">
                                    <label for="exampleformcontroltextarea1">açıklama</label>
                                    <textarea class="form-control" id="exampleformcontroltextarea1" rows="3"></textarea>
                                    <input class="input100" type="number" asp-for="@item.Amount" placeholder="Miktar" required>
                                </div>*@
                            </div>
                        </div>
                    </div>
                    }

            }
    </div>
</div>